---
title: "main."
author: "Molly K"
date: "04/11/2020"
output: "html_document"
---
<!-- Setup, FALSE for these 3 so code doesn't show up in document -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

<!-- package loading -->
```{r packages}
library(tidyverse)

```

# Introduction 
Working with the **chaff** data set, this data records the masses of male and female chaffinches.  

## Methods
Use R analysis to calculate the **sum of squares** from the **mass** values. 

```{r data}
# read in chaff data
chaff <- read.table("raw_data/chaff.txt", header = TRUE)
str(chaff)

# tidy chaff data
chaff2 <- pivot_longer(data = chaff, cols = everything(),
                       names_to = "sex", values_to = "mass")
str(chaff2)
file <-  "../chaff/chaff2.txt"
# save to file 
write.table(chaff2, 
            file, 
            quote = FALSE,
            row.names = FALSE)
```
<!-- code chunk for SS(x) -->
```{r analysis}
sum_sq <- function(df, measure) {
  df %>% summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff2, mass)

# adapt to calculate SS(x) for each group
sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff2, mass, sex)
```

### Results 
The difference in masses between sex. The *SS(x)* values for **females** is **86.8320**, whilst for **males** it is **87.8975**.

#### Discussion 